# Generated by Django 5.1.5 on 2025-08-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_user_alter_url_short_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user',
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
